Repository Dintero/Dintero.Checkout.WooCommerce, pull requests merged in 2021-08, with the labels that each got.

#72 Fix VAT set with two extra zeros
  includes/class-wc-dintero-hp-checkout.php
Labels: bug, woocommerce

#73 Fix double Checkout Express button
  includes/class-wc-dintero-hp.php
Labels: bug, woocommerce

#75 Fix issue with wrong shipping option when creating order from callback
  includes/class-wc-dintero-hp-ajax.php
Labels: bug, woocommerce

#77 Fix exit code from phpunit.sh script on test failure
  bin/phpunit.sh
Labels: enhancement, woocommerce

#70 Fix issue with ON_HOLD after order is pending
  README.md
  README.txt
  dintero-hp.php
  includes/class-wc-dintero-hp-ajax.php
  tests/phpunit/test-ajax.php
Labels: woocommerce

#81 Fix issue for embedded shipping options where order is not updated after cart update
  README.txt
  dintero-hp.php
  includes/class-wc-dintero-hp-checkout.php
Labels: bug, woocommerce

#83 Fix missing metadata when order created with callback
  includes/class-wc-dintero-hp-ajax.php
Labels: woocommerce

#85 Fix shipping_option problems
  README.txt
  dintero-hp.php
  includes/class-wc-dintero-hp-ajax.php
  includes/class-wc-dintero-hp-checkout.php
  includes/class-wc-dintero-hp-helper.php
  includes/class-wc-dintero-hp.php
  includes/class-wc-gateway-dintero-hp.php
  tests/manual/shipping_in_iframe.md
  tests/phpunit/helpers/class-wc-helper-order.php
  tests/phpunit/test-ajax.php
  tests/phpunit/test-class-wc-dintero-hp-checkout.php
  tests/phpunit/test-class-wc-gateway-dintero-hp.php
Labels: bug, woocommerce
